    - name: Instalando repositorio UBUNTU -  PUppet 
      command: dpkg -i /root/puppet5-release-xenial.deb
      when: ansible_os_family == "Debian"

    - name: Instlando Puppet Agent - UBUNTU
      apt: 
        name: puppet-agent
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

